"""
database.py
===========
Phase 4 — SQLite database layer.

Stores all historical data locally so you can:
  - Track how signals performed over time
  - See if Buy signals actually led to gains
  - Query "what was the signal for AAPL on 2025-03-15?"
  - Build a track record of the system's predictions
  - Run signal performance analytics

Tables:
  signals_history   — every signal generated, every day
  price_history     — daily OHLCV for all assets
  backtest_history  — backtest results per run
  alerts_history    — all alerts ever fired
  macro_history     — daily macro snapshots
  ml_predictions_history — ML predictions per day

Uses SQLite — no server needed, zero config, file-based.
Database file: data/trading_intelligence.db

All writes are append-only. Never deletes historical data.
"""

from __future__ import annotations

import json
import logging
import sqlite3
from contextlib import contextmanager
from datetime import date, datetime
from pathlib import Path
from typing import Dict, List, Optional, Any

import pandas as pd

logger = logging.getLogger(__name__)

DB_PATH = Path("data/trading_intelligence.db")


# ===========================================================================
# Connection manager
# ===========================================================================

@contextmanager
def get_connection():
    """Context manager for SQLite connections. Auto-commits and closes."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH), timeout=30)
    conn.row_factory = sqlite3.Row   # Enables dict-like access to rows
    conn.execute("PRAGMA journal_mode=WAL")   # Better concurrent access
    conn.execute("PRAGMA foreign_keys=ON")
    try:
        yield conn
        conn.commit()
    except Exception as e:
        conn.rollback()
        raise e
    finally:
        conn.close()


# ===========================================================================
# Schema creation
# ===========================================================================

SCHEMA = """
-- Every signal generated by the system, one row per asset per run date
CREATE TABLE IF NOT EXISTS signals_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date        TEXT NOT NULL,          -- YYYY-MM-DD
    ticker          TEXT NOT NULL,
    asset_class     TEXT,
    current_price   REAL,
    composite_score REAL,
    action          TEXT,
    confidence      TEXT,
    bullish_prob    REAL,
    bearish_prob    REAL,
    trend_score     REAL,
    momentum_score  REAL,
    volatility_score REAL,
    regime_score    REAL,
    macro_score     REAL,
    sentiment_score REAL,
    risk_level      TEXT,
    realised_vol    REAL,
    stop_loss       REAL,
    take_profit     REAL,
    position_size_pct REAL,
    regime          TEXT,
    explanation     TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Index for fast lookups by ticker + date
CREATE INDEX IF NOT EXISTS idx_signals_ticker_date
    ON signals_history(ticker, run_date);

-- Daily OHLCV price snapshots
CREATE TABLE IF NOT EXISTS price_history (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date    TEXT NOT NULL,
    ticker      TEXT NOT NULL,
    open_price  REAL,
    high_price  REAL,
    low_price   REAL,
    close_price REAL,
    volume      REAL,
    created_at  TEXT DEFAULT (datetime('now')),
    UNIQUE(run_date, ticker)
);

CREATE INDEX IF NOT EXISTS idx_price_ticker_date
    ON price_history(ticker, run_date);

-- Backtest results per run
CREATE TABLE IF NOT EXISTS backtest_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date        TEXT NOT NULL,
    ticker          TEXT NOT NULL,
    total_return    REAL,
    cagr            REAL,
    sharpe_ratio    REAL,
    sortino_ratio   REAL,
    max_drawdown    REAL,
    win_rate        REAL,
    n_trades        INTEGER,
    profit_factor   REAL,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- All alerts ever generated
CREATE TABLE IF NOT EXISTS alerts_history (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date    TEXT NOT NULL,
    alert_type  TEXT,
    severity    TEXT,
    ticker      TEXT,
    title       TEXT,
    message     TEXT,
    value       REAL,
    threshold   REAL,
    created_at  TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_alerts_severity
    ON alerts_history(severity, run_date);

-- Daily macro snapshots
CREATE TABLE IF NOT EXISTS macro_history (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date            TEXT NOT NULL UNIQUE,
    vix                 REAL,
    dxy                 REAL,
    dxy_trend           REAL,
    treasury_10y        REAL,
    yield_spread_10y2y  REAL,
    cpi_yoy             REAL,
    unemployment_rate   REAL,
    gold_trend_20d      REAL,
    macro_score         REAL,
    regime              TEXT,
    created_at          TEXT DEFAULT (datetime('now'))
);

-- ML predictions per asset per day
CREATE TABLE IF NOT EXISTS ml_predictions_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date        TEXT NOT NULL,
    ticker          TEXT NOT NULL,
    horizon_days    INTEGER,
    bullish_prob    REAL,
    bearish_prob    REAL,
    direction       TEXT,
    confidence      TEXT,
    model_agreement REAL,
    overall_signal  TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ml_ticker_date
    ON ml_predictions_history(ticker, run_date);

-- Signal performance tracking: did the signal turn out to be correct?
CREATE TABLE IF NOT EXISTS signal_performance (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_date     TEXT NOT NULL,
    ticker          TEXT NOT NULL,
    action          TEXT,
    composite_score REAL,
    entry_price     REAL,
    price_1d        REAL,    -- Actual price 1 day later
    price_5d        REAL,    -- Actual price 5 days later
    price_20d       REAL,    -- Actual price 20 days later
    return_1d       REAL,    -- Actual return 1 day later
    return_5d       REAL,
    return_20d      REAL,
    signal_correct_1d  INTEGER,   -- 1 if signal direction matched, 0 if not
    signal_correct_5d  INTEGER,
    signal_correct_20d INTEGER,
    updated_at      TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_perf_ticker_date
    ON signal_performance(ticker, signal_date);
"""


def initialise_database() -> None:
    """Create all tables if they don't already exist."""
    with get_connection() as conn:
        conn.executescript(SCHEMA)
    logger.info(f"Database initialised at {DB_PATH}")


# ===========================================================================
# Write functions
# ===========================================================================

def save_signals(signals: Dict[str, dict], run_date: Optional[str] = None) -> int:
    """
    Save all signals to signals_history table.
    Returns number of rows inserted.
    """
    today = run_date or str(date.today())
    rows = []

    for ticker, sig in signals.items():
        rows.append((
            today,
            ticker,
            sig.get("asset_class"),
            sig.get("current_price"),
            sig.get("composite_score"),
            sig.get("action"),
            sig.get("confidence"),
            sig.get("bullish_prob"),
            sig.get("bearish_prob"),
            sig.get("trend_score"),
            sig.get("momentum_score"),
            sig.get("volatility_score"),
            sig.get("regime_score"),
            sig.get("macro_score"),
            sig.get("sentiment_score"),
            sig.get("risk_level"),
            sig.get("realised_vol"),
            sig.get("stop_loss"),
            sig.get("take_profit"),
            sig.get("position_size_pct"),
            sig.get("regime"),
            sig.get("explanation", ""),
        ))

    with get_connection() as conn:
        conn.executemany("""
            INSERT INTO signals_history (
                run_date, ticker, asset_class, current_price, composite_score,
                action, confidence, bullish_prob, bearish_prob,
                trend_score, momentum_score, volatility_score, regime_score,
                macro_score, sentiment_score, risk_level, realised_vol,
                stop_loss, take_profit, position_size_pct, regime, explanation
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, rows)

    logger.info(f"Saved {len(rows)} signals to database for {today}")
    return len(rows)


def save_prices(raw_data: Dict[str, Any], run_date: Optional[str] = None) -> int:
    """Save latest OHLCV prices for all assets."""
    today = run_date or str(date.today())
    rows = []

    for ticker, df in raw_data.items():
        if df is None or df.empty:
            continue
        try:
            last = df.iloc[-1]
            rows.append((
                today, ticker,
                float(last.get("Open",  last.get("open",  0))),
                float(last.get("High",  last.get("high",  0))),
                float(last.get("Low",   last.get("low",   0))),
                float(last.get("Close", last.get("close", 0))),
                float(last.get("Volume", last.get("volume", 0)) or 0),
            ))
        except Exception:
            continue

    with get_connection() as conn:
        conn.executemany("""
            INSERT OR REPLACE INTO price_history
            (run_date, ticker, open_price, high_price, low_price, close_price, volume)
            VALUES (?,?,?,?,?,?,?)
        """, rows)

    logger.info(f"Saved {len(rows)} price rows to database for {today}")
    return len(rows)


def save_backtest_results(backtest_data: dict, run_date: Optional[str] = None) -> int:
    """Save backtest metrics to database."""
    today = run_date or str(date.today())
    rows = []

    for ticker, result in backtest_data.items():
        m = result.get("metrics", {})
        rows.append((
            today, ticker,
            m.get("total_return"),
            m.get("cagr"),
            m.get("sharpe_ratio"),
            m.get("sortino_ratio"),
            m.get("max_drawdown"),
            m.get("win_rate"),
            m.get("n_trades"),
            m.get("profit_factor"),
        ))

    with get_connection() as conn:
        conn.executemany("""
            INSERT INTO backtest_history
            (run_date, ticker, total_return, cagr, sharpe_ratio, sortino_ratio,
             max_drawdown, win_rate, n_trades, profit_factor)
            VALUES (?,?,?,?,?,?,?,?,?,?)
        """, rows)

    return len(rows)


def save_alerts(alerts: list, run_date: Optional[str] = None) -> int:
    """Save alerts list to database."""
    today = run_date or str(date.today())
    rows = []

    for a in alerts:
        rows.append((
            today,
            a.get("alert_type"),
            a.get("severity"),
            a.get("ticker"),
            a.get("title"),
            a.get("message"),
            a.get("value"),
            a.get("threshold"),
        ))

    with get_connection() as conn:
        conn.executemany("""
            INSERT INTO alerts_history
            (run_date, alert_type, severity, ticker, title, message, value, threshold)
            VALUES (?,?,?,?,?,?,?,?)
        """, rows)

    return len(rows)


def save_macro(macro: dict, run_date: Optional[str] = None) -> None:
    """Save macro snapshot to database."""
    today = run_date or str(date.today())
    with get_connection() as conn:
        conn.execute("""
            INSERT OR REPLACE INTO macro_history
            (run_date, vix, dxy, dxy_trend, treasury_10y, yield_spread_10y2y,
             cpi_yoy, unemployment_rate, gold_trend_20d, macro_score, regime)
            VALUES (?,?,?,?,?,?,?,?,?,?,?)
        """, (
            today,
            macro.get("vix"),
            macro.get("dxy"),
            macro.get("dxy_trend"),
            macro.get("treasury_10y"),
            macro.get("yield_spread_10y2y"),
            macro.get("cpi_yoy"),
            macro.get("unemployment_rate"),
            macro.get("gold_trend_20d"),
            macro.get("macro_score"),
            macro.get("regime"),
        ))


def save_ml_predictions(ml_data: dict, run_date: Optional[str] = None) -> int:
    """Save ML predictions to database."""
    today = run_date or str(date.today())
    rows = []

    for ticker, pred in ml_data.items():
        for h_str, hp in pred.get("horizons", {}).items():
            rows.append((
                today, ticker,
                hp.get("horizon_days"),
                hp.get("bullish_prob"),
                hp.get("bearish_prob"),
                hp.get("direction"),
                hp.get("confidence"),
                hp.get("model_agreement"),
                pred.get("overall_signal"),
            ))

    with get_connection() as conn:
        conn.executemany("""
            INSERT INTO ml_predictions_history
            (run_date, ticker, horizon_days, bullish_prob, bearish_prob,
             direction, confidence, model_agreement, overall_signal)
            VALUES (?,?,?,?,?,?,?,?,?)
        """, rows)

    return len(rows)


# ===========================================================================
# Read / Query functions
# ===========================================================================

def get_signal_history(ticker: str, days: int = 30) -> pd.DataFrame:
    """Get signal history for one ticker over the last N days."""
    with get_connection() as conn:
        df = pd.read_sql_query("""
            SELECT run_date, composite_score, action, confidence,
                   bullish_prob, realised_vol, regime, current_price
            FROM signals_history
            WHERE ticker = ?
            ORDER BY run_date DESC
            LIMIT ?
        """, conn, params=(ticker, days))
    return df


def get_all_signals_for_date(run_date: str) -> pd.DataFrame:
    """Get all signals generated on a specific date."""
    with get_connection() as conn:
        df = pd.read_sql_query("""
            SELECT * FROM signals_history
            WHERE run_date = ?
            ORDER BY composite_score DESC
        """, conn, params=(run_date,))
    return df


def get_macro_history(days: int = 90) -> pd.DataFrame:
    """Get macro history over last N days."""
    with get_connection() as conn:
        df = pd.read_sql_query("""
            SELECT * FROM macro_history
            ORDER BY run_date DESC
            LIMIT ?
        """, conn, params=(days,))
    return df.sort_values("run_date") if not df.empty else df


def get_alert_history(severity: Optional[str] = None, days: int = 30) -> pd.DataFrame:
    """Get alert history, optionally filtered by severity."""
    with get_connection() as conn:
        if severity:
            df = pd.read_sql_query("""
                SELECT * FROM alerts_history
                WHERE severity = ?
                ORDER BY run_date DESC
                LIMIT 200
            """, conn, params=(severity,))
        else:
            df = pd.read_sql_query("""
                SELECT * FROM alerts_history
                ORDER BY run_date DESC
                LIMIT 200
            """, conn)
    return df


def get_best_performing_signals(min_score: float = 40, days: int = 90) -> pd.DataFrame:
    """
    Get signals with score > threshold and check subsequent price performance.
    Used to validate: do high-score Buy signals actually go up?
    """
    with get_connection() as conn:
        df = pd.read_sql_query("""
            SELECT s.run_date, s.ticker, s.action, s.composite_score,
                   s.current_price, s.confidence,
                   p.return_1d, p.return_5d, p.return_20d,
                   p.signal_correct_1d, p.signal_correct_5d, p.signal_correct_20d
            FROM signals_history s
            LEFT JOIN signal_performance p
                ON s.ticker = p.ticker AND s.run_date = p.signal_date
            WHERE s.composite_score >= ?
            ORDER BY s.run_date DESC
            LIMIT 100
        """, conn, params=(min_score,))
    return df


def get_database_stats() -> dict:
    """Return stats about what's stored in the database."""
    with get_connection() as conn:
        stats = {}
        for table in ["signals_history", "price_history", "alerts_history",
                      "macro_history", "ml_predictions_history", "backtest_history"]:
            try:
                count = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
                stats[table] = count
            except Exception:
                stats[table] = 0

        # Date range of signals
        try:
            row = conn.execute(
                "SELECT MIN(run_date), MAX(run_date) FROM signals_history"
            ).fetchone()
            stats["signals_date_range"] = {"from": row[0], "to": row[1]}
        except Exception:
            stats["signals_date_range"] = {}

    return stats


def update_signal_performance(raw_data: Dict[str, Any], run_date: Optional[str] = None) -> None:
    """
    Update signal_performance table with actual future prices.
    Run this daily to see how last week's signals performed.

    For each signal from 1, 5, 20 days ago, record the actual price
    and compute whether the signal direction was correct.
    """
    today = run_date or str(date.today())

    with get_connection() as conn:
        # Get signals from the past that need price updates
        pending = pd.read_sql_query("""
            SELECT DISTINCT s.ticker, s.run_date, s.composite_score,
                            s.action, s.current_price
            FROM signals_history s
            LEFT JOIN signal_performance p
                ON s.ticker = p.ticker AND s.run_date = p.signal_date
            WHERE p.id IS NULL
              AND s.run_date >= date(?, '-25 days')
        """, conn, params=(today,))

    if pending.empty:
        return

    for _, row in pending.iterrows():
        ticker     = row["ticker"]
        sig_date   = row["run_date"]
        entry_px   = row["current_price"]
        score      = row["composite_score"]

        if ticker not in raw_data or raw_data[ticker] is None:
            continue

        try:
            close = raw_data[ticker]["Close"].squeeze()
            # Find the signal date in the price index
            close.index = pd.to_datetime(close.index)
            sig_dt = pd.to_datetime(sig_date)

            future_prices = close[close.index > sig_dt]
            if future_prices.empty:
                continue

            def _get_return(n_days):
                if len(future_prices) >= n_days:
                    px = float(future_prices.iloc[n_days - 1])
                    ret = (px / entry_px - 1) if entry_px else None
                    correct = 1 if (score > 0 and ret > 0) or (score < 0 and ret < 0) else 0
                    return px, ret, correct
                return None, None, None

            px1,  r1,  c1  = _get_return(1)
            px5,  r5,  c5  = _get_return(5)
            px20, r20, c20 = _get_return(20)

            with get_connection() as conn:
                conn.execute("""
                    INSERT OR REPLACE INTO signal_performance
                    (signal_date, ticker, action, composite_score, entry_price,
                     price_1d, price_5d, price_20d,
                     return_1d, return_5d, return_20d,
                     signal_correct_1d, signal_correct_5d, signal_correct_20d)
                    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """, (
                    sig_date, ticker, row["action"], score, entry_px,
                    px1, px5, px20, r1, r5, r20, c1, c5, c20,
                ))
        except Exception as e:
            logger.debug(f"Performance update failed for {ticker}: {e}")

    logger.info(f"Updated signal performance for {len(pending)} signals")
